# Generated by Django 5.1.2 on 2024-12-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_urls',
            field=models.URLField(blank=True, null=True),
        ),
    ]
