# Generated by Django 5.1.2 on 2024-12-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_alter_recipe_image_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='average_rating',
        ),
    ]
