# Generated by Django 5.1.2 on 2024-12-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0003_remove_recipe_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='video_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='recipes/videos/'),
        ),
    ]
